################
# - ANN
# - all parameters evolved
# - divergence as input

log location: logs/runs/
log interval: 20
evo:
  gens: 200
  pop size: 100
  mutation rate: 0.3
  genes: [weight, bias]
  types: []
  obj weights: [-1.0, -1.0, -1.0]
  obj optimal: [[1.0, 0.05, 0.0]]
  obj worst: [100.0, 10.0, 10.0]
  objectives: [time to land, final height, final velocity]  # second dim not plotted in relevant (so put least important here)
  plot 2D: [[0, 2]]  # combinations of objectives to plot in 2D
  plot 3D: [[0, 1, 2]]  # combinations of objectives to plot in 3D
env:
  # Lists (except thrust bounds) indicate randomization bounds
  delay: [1, 4]
  noise: [0.05, 0.15]
  noise p: [0.0, 0.25]
  g: 1.0
  g bounds: [-7.848, 4.905]
  thrust tc: [0.005, 0.04]
  settle: 0.5
  wind: 0.1
  h0: [2.0, 4.0, 6.0, 8.0]
  dt: [0.02, 0.0333]
  ds act: [1, 2]  # don't use this, superfluous
  jitter: [0.0, 0.2]
  max time: 30.0
  seeds: 100
net:
  network: ANN
  hidden size: 20
  encoding: divergence
