log location: logs/runs/
log interval: 20
evo:
  gens: 200
  pop size: 100
  mutation rate: 0.3
  genes: [weight, bias]
  types: []
  obj weights: [-1.0, -1.0, -1.0]
  objectives: [time to land, final height, final velocity linear]  # second dim not plotted in relevant (so put least important here)
env:
  # Lists (except thrust bounds) indicate randomization bounds
  delay: [3, 6]
  noise: [0.1, 0.15]
  noise p: [0.1, 0.25]
  g: 9.81
  g bounds: [-0.8, 0.5]
  thrust tc: [0.02, 0.1]
  settle: 0.5
  wind: 0.1
  h0: [2.0, 4.0, 6.0, 8.0]
  dt: [0.02, 0.02]
  ds act: [1, 2]
  jitter: [0.0, 0.0]
  max time: 30.0
  seeds: 100
net:
  network: ANN
  hidden size: 20
  encoding: both
