log location: logs/
log interval: 5
network: ANN
hidden size: 8
evo:
  gens: 50
  pop size: 100
  mutation rate: 0.3
  genes: ["weight", "bias"]
  obj weights: [-1.0, 1.0, -1.0]
  objectives: ["final offset", "air time", "unsigned divergence"]  # second dim not plotted in relevant (so put least important here)
env:
  # Lists (except thrust bounds) indicate randomization bounds
  delay: [3, 6]
  noise: [0.1, 0.15]
  noise p: [0.1, 0.25]
  thrust bounds: [-0.8, 0.5]  # in G's
  thrust tc: [0.02, 0.1]
  settle: 1.0
  wind: 0.1
  h0: [2.0, 6.0]
  dt: 0.02
  max time: 5.0
  seeds: 100
