log location: logs/
log interval: 5
network: ANN
hidden size: 20
evo:
  gens: 100
  pop size: 100
  mutation rate: 0.3
  genes: [weight, bias]
  obj weights: [-1.0, -1.0, -1.0]
  objectives: [time to land, final height, final velocity]  # second dim not plotted in relevant (so put least important here)
env:
  # Lists (except thrust bounds) indicate randomization bounds
  delay: [3, 6]
  noise: [0.1, 0.15]
  noise p: [0.1, 0.25]
  thrust bounds: [-0.8, 0.5]  # in G's
  thrust tc: [0.02, 0.1]
  settle: 1.0
  wind: 0.1
  h0: [2.0, 4.0, 6.0, 8.0]
  dt: 0.02
  max time: 30.0
  seeds: 100
