log location: logs/cases/
log interval: 10
evo:
  gens: 200
  pop size: 100
  mutation rate: 0.3
  genes: [weight]
  types: []
  obj weights: [-1.0, -1.00]
  obj optimal: [[0.0, 0.0]]
  obj worst: [10000.0, 0.0]
  objectives: [SSE D0.5, dummy]
  plot: [[0, 1]]  # combinations of objectives to plot
env:
  # Lists (except thrust bounds) indicate randomization bounds
  delay: [1, 4]
  noise: [0.05, 0.15]
  noise p: [0.0, 0.25]
  g: 1.0
  g bounds: [-7.848, 4.905]
  thrust tc: [0.005, 0.04]
  settle: 0.5
  wind: 0.1
  h0: [2.0, 4.0, 6.0, 8.0]
  dt: [0.02, 0.0333]
  ds act: [1, 2]  # don't use this, superfluous
  jitter: [0.0, 0.2]
  max time: 30.0
  seeds: 100
net:
  network: ANN
  hidden size: 2
  encoding: both
