log location: logs/
log interval: 25
gens: 250
pop size: 100
mutation rate: 0.3
network: ANN
hidden size: 8
scenario: hover
env:
  delay: [1, 6]
  comp delay prob: 0.0
  noise: [0.0, 0.15]
  noise p: [0.0, 0.25]
  thrust tc: [0.02, 0.1]
  settle: 1.0
  wind: 0.1
  h0: [2.0, 4.0, 6.0, 8.0]
  dt: 0.02
  seeds: 100
