#### Case 2a ####
# - SNN
# - alphas and taus per neuron
# - all parameters evolved
# - optimization for spikes
# - uniformly distributed divergence place cells as input

log location: logs/cases/
log interval: 50
evo:
  gens: 400
  pop size: 100
  mutation rate: 0.3
  genes: [weight, alpha_v, alpha_t, alpha_thresh, tau_v, tau_t, tau_thresh, thresh]
  types: [all]
  obj weights: [-1.0, -1.0, -1.0, -1.0]
  obj optimal: [[1.0, 0.05, 0.0, 0.0]]
  obj worst: [100.0, 10.0, 10.0, 1000.0]
  objectives: [time to land, final height, final velocity, spikes]
  plot: [[0, 2], [0, 3]]  # combinations of objectives to plot
env:
  # Lists (except thrust bounds) indicate randomization bounds
  delay: [1, 4]
  noise: [0.05, 0.15]
  noise p: [0.0, 0.25]
  g: 9.81
  g bounds: [-0.8, 0.5]
  thrust tc: [0.005, 0.04]
  settle: 0.5
  wind: 0.1
  h0: [2.0, 4.0, 6.0, 8.0]
  dt: [0.02, 0.0333]
  ds act: [1, 2]  # don't use this, superfluous
  jitter: [0.0, 0.2]
  max time: 30.0
  seeds: 100
net:
  # Lists allow separate parameters for each spiking layer
  network: SNN
  hidden size: 20
  neuron: [adaptive, regular]
  thresh: [0.2, 0.2]
  v rest: [0.0, 0.0]
  alpha v: [0.2, 0.2]
  alpha t: [1.0, 1.0]
  alpha thresh: [0.2, 0.2]
  tau v: [0.8, 0.8]
  tau t: [0.8, 0.8]
  tau thresh: [0.8, 0.8]
  refrac: [0, 0]
  dt: 1
  delay: 0
  input bound: 10.0  # only used for place encoding
  input size: 11  # only used for place encoding
  input scale: 1.0  # only used for place encoding
  output scale: 1.0  # find proper value for this!
  output offset: 0.0
  encoding: place uniform
  decoding: single trace
