log location: logs/
log interval: 5
network: SNN
double neurons: False
double actions: False
hidden size: 8
evo:
  gens: 50
  pop size: 100
  mutation rate: 0.3
  genes: ["weight"]
  obj weights: [-1.0, 1.0, -1.0]
  objectives: ["signed divergence", "air time", "final offset"]  # second dim not plotted in relevant (so put least important here)
env:
  # Lists (except thrust bounds) indicate randomization bounds
  delay: [0, 1]
  comp delay prob: 0.0
  noise: [0.0, 0.0]
  noise p: [0.0, 0.0]
  thrust bounds: [-0.8, 0.5]  # in G's
  thrust tc: [0.02, 0.02]
  settle: 1.0
  wind: 0.0
  h0: [2.0, 4.0, 6.0, 8.0]
  dt: 0.02
  seeds: 100
snn:
  # Lists allow separate parameters for each spiking layer
  thresh: [0.8, 0.8]
  v rest: [0.0, 0.0]
  alpha v: [0.2, 0.2]
  alpha t: [0.4, 0.4]
  tau v: [0.8, 0.8]
  tau t: [0.8, 0.8]
  refrac: [0, 0]
  dt: 1
  delay: 0
  input scale: 0.1
  input offset: 1.0
  output scale: 1.0  # find proper value for this!
  output offset: 0.0
  decoding: trace
