log location: logs/
log interval: 20
network: SNN
double neurons: True
double actions: False
hidden size: 20
evo:
  gens: 200
  pop size: 100
  mutation rate: 0.3
  genes: [weight, alpha_v, alpha_t, alpha_thresh, tau_v, tau_t, tau_thresh, thresh]
  types: []
  obj weights: [-1.0, -1.0, -1.0]
  objectives: [time to land, final height, final velocity]  # second dim not plotted in relevant (so put least important here)
env:
  # Lists (except thrust bounds) indicate randomization bounds
  delay: [3, 6]
  noise: [0.1, 0.15]
  noise p: [0.1, 0.25]
  thrust bounds: [-0.8, 0.5]  # in G's
  thrust tc: [0.02, 0.1]
  settle: 1.0
  wind: 0.1
  h0: [2.0, 4.0, 6.0, 8.0]
  dt: 0.02
  max time: 30.0
  seeds: 100
snn:
  # Lists allow separate parameters for each spiking layer
  neuron: [adaptive, regular]
  thresh: [0.2, 0.2]
  v rest: [0.0, 0.0]
  alpha v: [0.2, 0.2]
  alpha t: [1.0, 1.0]
  alpha thresh: [0.2, 0.2]
  tau v: [0.8, 0.8]
  tau t: [0.8, 0.8]
  tau thresh: [0.9, 0.9]
  refrac: [0, 0]
  dt: 1
  delay: 0
  input scale: 0.1
  input offset: 1.0
  output scale: 1.0  # find proper value for this!
  output offset: 0.0
  decoding: trace
